sudo: false
language: java

jdk:
  - oraclejdk12

before_install:
- export MESSAGE_QUEUE_HOST='localhost:9092'
- wget http://apache.claz.org/kafka/1.0.0/kafka_2.11-1.0.0.tgz -O kafka.tgz
- mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
- nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
- sleep 10
- nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
- sleep 10
- kafka/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test
- sleep 10
- kafka/bin/kafka-topics.sh --list --zookeeper localhost:2181

install:
- gradle assemble -x signArchives

script:
- ./gradlew check -x signArchives -i

after_success:
- kafka/bin/kafka-server-stop.sh
- kafka/bin/zookeeper-server-stop.sh

after_failure:
- echo "------- TEST MESSAGES ------"
- cat kafka/logs/test_msgs.log
- echo "------- SERVER LOG -------"
- cat kafka/logs/server.log
